name: MergeActions

on:
  push:
    branches:
    - dev
  milestone:
    types: [created, edited]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "dev"
        destination_branch: "master"
        pr_title: "Pulling ${{ github.ref }} into MASTER"
        pr_body: ":crown: *An automated PR*  This PR will pull all recent merges from DEV into MASTER. If you just completed a merge into develop, please wait 8-10 minutes for any build stages to complete before merging this PR."
        pr_label: "auto-pr from dev to master"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
  zap_scan:
    runs-on: ubuntu-latest
    name: Zap Scan MMTI Public
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://www-mem-mmt-dev.pathfinder.gov.bc.ca/'
          rules_file_name: '.zap/rules.tsv'
